from collections import OrderedDict
from appdirs import user_config_dir
import os
import re
SCHEDULE_FILE = '/home/sun3000/infill/src/conf/schedule.json'
CONFIG_FILE = '/home/sun3000/infill/src/conf/conf.ini'
slicer_configs = OrderedDict([
    ('Quality', (
        ('layer_height', float, 0.2, (0.01, 0.5), "Slice layer height in mm."),
        ('shell_count', int, 0, (0, 10), "Number of outer shells to print."),
        ('shell_speed', float, 0, (0, 500), "The shell speed (mm/s)"),
        # ('outer_shell_speed',  float,   20, (1, 500),    "The outer shell speed (mm/s)"),
        ('random_starts', bool, True, None, "Enable randomizing of perimeter starts."),
        ('top_layers', int, 0, (0, 10), "Number of layers to print on the top side of the object."),
        ('bottom_layers', int, 0, (0, 10), "Number of layers to print on the bottom side of the object."),
        # Lines:45-135, Lines1 : 0-90, Lines2: 0-45-90-135
        ('infill_type', list, 'Lines-0-90', ['Lines', 'Lines-0-90', 'Lines-0-45-90-135' 'Triangles', 'Grid', 'Hexagons', 'Honeycomb', 'Circle'],
         "Pattern that the infill will be printed in."),
        ('infill_density', float, 30., (0., 100.), "Infill density in percent."),
        (
        'infill_overlap', float, 0.30, (0.0, 1.0), "Amount, in mm that infill will overlap with perimeter extrusions."),
        ('feed_rate', int, 60, (1, 300), "Speed while extruding. (mm/s)"),
        ('travel_rate_xy', int, 100, (1, 300), "Travel motion speed (mm/s)"),
        ('travel_rate_z', float, 5., (0.1, 30.), "Z-axis  motion speed (mm/s)"),
    )),
    ('Support', (
        (
        'support_type', list, 'External', ('None', 'External', 'Everywhere'), "What kind of support structure to add."),
        ('support_outset', float, 0.5, (0., 2.),
         "How far support structures should be printed away from model, horizontally."),
        ('support_density', float, 33.0, (0., 100.), "Density of support structure internals."),
        ('overhang_angle', int, 45, (0, 90), "Angle from vertical that support structures should be printed for."),
    )),
    ('Adhesion', (
        ('adhesion_type', list, 'None', ('None', 'Brim', 'Raft'), "What kind of base adhesion structure to add."),
        ('brim_width', float, 3.0, (0., 20.), "Width of brim to print on first layer to help with part adhesion."),
        ('raft_layers', int, 3, (1, 5), "Number of layers to use in making the raft."),
        ('raft_outset', float, 3.0, (0., 50.), "How much bigger raft should be than the model footprint."),
        ('skirt_outset', float, 3.0, (0., 20.), "How far the skirt should be printed away from model."),
        ('skirt_layers', int, 0, (0, 1000), "Number of layers to print the skirt on."),
        ('skirt_lines', int, 2, (0, 1000), "Number of skirt lines to print."),
        ('prime_length', float, 0, (0., 1000.), "Length of filament to extrude when priming hotends."),
    )),
    ('Retraction', (
        ('retract_enable', bool, True, None, "Enable filament retraction."),
        ('retract_speed', float, 60.0, (0., 200.), "Speed to retract filament at. (mm/s)"),
        ('retract_dist', float, 3.0, (0., 20.), "Distance to retract filament between extrusion moves. (mm)"),
        ('retract_extruder', float, 3.0, (0., 50.), "Distance to retract filament on extruder change. (mm)"),
        ('retract_lift', float, 0.0, (0., 10.), "Distance to lift the extruder head during retracted moves. (mm)"),
    )),
    ('Materials', (
        ('abs_bed_temp', int, 90, (0, 150), "The bed temperature to use for ABS filament. (C)"),
        ('abs_hotend_temp', int, 230, (150, 300), "The extruder temperature to use for ABS filament. (C)"),
        ('abs_max_speed', float, 75.0, (0, 150), "The maximum speed when extruding ABS filament. (mm/s)"),
        ('hips_bed_temp', int, 100, (0, 150), "The bed temperature to use for dissolvable HIPS filament. (C)"),
        (
        'hips_hotend_temp', int, 230, (150, 300), "The extruder temperature to use for dissolvable HIPS filament. (C)"),
        ('hips_max_speed', float, 30.0, (0, 150), "The maximum speed when extruding dissolvable HIPS filament. (mm/s)"),
        ('nylon_bed_temp', int, 70, (0, 150), "The bed temperature to use for Nylon filament. (C)"),
        ('nylon_hotend_temp', int, 255, (150, 300), "The extruder temperature to use for Nylon filament. (C)"),
        ('nylon_max_speed', float, 75.0, (0, 150), "The maximum speed when extruding Nylon filament. (mm/s)"),
        ('pc_bed_temp', int, 130, (0, 150), "The bed temperature to use for Polycarbonate filament. (C)"),
        ('pc_hotend_temp', int, 290, (150, 300), "The extruder temperature to use for Polycarbonate filament. (C)"),
        ('pc_max_speed', float, 75.0, (0, 150), "The maximum speed when extruding Polycarbonate filament. (mm/s)"),
        ('pet_bed_temp', int, 70, (0, 150), "The bed temperature to use for PETG/PETT filament. (C)"),
        ('pet_hotend_temp', int, 230, (150, 300), "The extruder temperature to use for PETG/PETT filament. (C)"),
        ('pet_max_speed', float, 75.0, (0, 150), "The maximum speed when extruding PETG/PETT filament. (mm/s)"),
        ('pla_bed_temp', int, 45, (0, 150), "The bed temperature to use for PLA filament. (C)"),
        ('pla_hotend_temp', int, 205, (150, 300), "The extruder temperature to use for PLA filament. (C)"),
        ('pla_max_speed', float, 75.0, (0, 150), "The maximum speed when extruding PLA filament. (mm/s)"),
        ('pp_bed_temp', int, 110, (0, 150), "The bed temperature to use for Polypropylene filament. (C)"),
        ('pp_hotend_temp', int, 250, (150, 300), "The extruder temperature to use for Polypropylene filament. (C)"),
        ('pp_max_speed', float, 75.0, (0, 150), "The maximum speed when extruding Polypropylene filament. (mm/s)"),
        ('pva_bed_temp', int, 60, (0, 150), "The bed temperature to use for dissolvable PVA filament. (C)"),
        ('pva_hotend_temp', int, 220, (150, 300), "The extruder temperature to use for dissolvable PVA filament. (C)"),
        ('pva_max_speed', float, 30.0, (0, 150), "The maximum speed when extruding dissolvable PVA filament. (mm/s)"),
        ('softpla_bed_temp', int, 30, (0, 150), "The bed temperature to use for flexible SoftPLA filament. (C)"),
        ('softpla_hotend_temp', int, 230, (150, 300),
         "The extruder temperature to use for flexible SoftPLA filament. (C)"),
        ('softpla_max_speed', float, 30.0, (0, 150),
         "The maximum speed when extruding flexible SoftPLA filament. (mm/s)"),
        ('tpe_bed_temp', int, 30, (0, 150), "The bed temperature to use for flexible TPE filament. (C)"),
        ('tpe_hotend_temp', int, 220, (150, 300), "The extruder temperature to use for flexible TPE filament. (C)"),
        ('tpe_max_speed', float, 30.0, (0, 150), "The maximum speed when extruding flexible TPE filament. (mm/s)"),
        ('tpu_bed_temp', int, 50, (0, 150), "The bed temperature to use for flexible TPU filament. (C)"),
        ('tpu_hotend_temp', int, 250, (150, 300), "The extruder temperature to use for flexible TPU filament. (C)"),
        ('tpu_max_speed', float, 30.0, (0, 150), "The maximum speed when extruding flexible TPU filament. (mm/s)"),
    )),
    ('Machine', (
        ('bed_geometry', list, 'Rectangular', ('Rectangular', 'Cylindrical'),
         "The shape of the build volume cross-section."),
        ('bed_size_x', float, 200, (0, 1000), "The X-axis size of the build platform bed."),
        ('bed_size_y', float, 200, (0, 1000), "The Y-axis size of the build platform bed."),
        ('bed_center_x', float, 0, (-500, 500), "The X coordinate of the center of the bed."),
        ('bed_center_y', float, 0, (-500, 500), "The Y coordinate of the center of the bed."),
        ('bed_temp', int, 70, (0, 150), "The temperature to set the heated bed to."),

        ('extruder_count', int, 1, (1, 16), "The number of extruders this machine has."),
        ('default_nozzle', int, 0, (0, 4), "The default extruder used for printing."),
        ('infill_nozzle', int, -1, (-1, 4), "The extruder used for infill material.  -1 means use default nozzle."),
        ('support_nozzle', int, -1, (-1, 4), "The extruder used for support material.  -1 means use default nozzle."),
        ('cool_fan_speed_max', float, 100, (0, 100), "The fan speed max (%)"),
        ('cool_fan_speed_min', float, 20, (0, 100), "The fan speed min (%)"),
        ('cool_fan_full_layer', int, 2, (0, 1000), "The layer the cool fan runs at max (layer)"),
        ('bridge_fan_speed', float, 100, (0, 100), "The fan speed min (%)"),

        ('start_gcode', str, 'G28 X0 Y0 ;auto-home all axes\nG28 Z0 ;auto-home all axes', None, "The starting Gcode"),
        ('end_gcode', str, 'G91 ;relative position\nG1 Z1\nG28 X ;home X-wise\nM84 ;motors off\nG90 ;absolute positioning', None, "The end Gcode"),
        ('gcode_comments', bool, True, None, "Enable/disable Gcode comments"),
        ('random_pos', bool, False, None, "Enable/disable random positioning of model"),

        ('nozzle_0_temp', int, 190, (150, 250), "The temperature of the nozzle for extruder 0. (C)"),
        ('nozzle_0_filament', float, 1.75, (1.0, 3.5), "The diameter of the filament for extruder 0. (mm)"),
        ('nozzle_0_diam', float, 0.4, (0.1, 1.5), "The diameter of the nozzle for extruder 0. (mm)"),
        ('nozzle_0_xoff', float, 0.0, (-100, 100), "The X positional offset for extruder 0. (mm)"),
        ('nozzle_0_yoff', float, 0.0, (-100, 100), "The Y positional offset for extruder 0. (mm)"),
        ('nozzle_0_zoff', float, 0.0, (-100, 100), "The Y positional offset for extruder 0. (mm)"),
        ('nozzle_0_max_speed', float, 75.0, (0., 200.), "The maximum speed when using extruder 0. (mm/s)"),
        ('nozzle_0_feed_rate', float, 10, (0., 25.), "The feed_rate when using extruder 0. (mm/s)"),
        ('nozzle_0_flow_rate', float, 0.5, (0., 1.), "The flow rate when using extruder 0."),
        ('nozzle_0_pre_extrude', float, 0.5, (0., 1.), "The pre extrusion when using extruder 0."),
        ('nozzle_0_retract', float, 0.5, (0., 1.), "The retract when using extruder 0."),

        ('nozzle_1_temp', int, 190, (150, 250), "The temperature of the nozzle for extruder 1. (C)"),
        ('nozzle_1_filament', float, 1.75, (1.0, 3.5), "The diameter of the filament for extruder 1. (mm)"),
        ('nozzle_1_diam', float, 0.4, (0.1, 1.5), "The diameter of the nozzle for extruder 1. (mm)"),
        ('nozzle_1_xoff', float, 0, (-100, 100), "The X positional offset for extruder 1. (mm)"),
        ('nozzle_1_yoff', float, 0.0, (-100, 100), "The Y positional offset for extruder 1. (mm)"),
        ('nozzle_1_zoff', float, 0.0, (-100, 100), "The Y positional offset for extruder 1. (mm)"),
        ('nozzle_1_max_speed', float, 75.0, (0., 200.), "The maximum speed when using extruder 1. (mm/s)"),
        ('nozzle_1_feed_rate', float, 5.0, (0., 25.), "The feed_rate when using extruder 1. (mm/s)"),
        ('nozzle_1_flow_rate', float, 0.5, (0., 1.), "The flow_rate when using extruder 1."),
        ('nozzle_1_pre_extrude', float, 0.5, (0., 1.), "The pre extrusion when using extruder 1."),
        ('nozzle_1_retract', float, 0.5, (0., 1.), "The retract when using extruder 1."),

        ('nozzle_2_temp', int, 190, (150, 250), "The temperature of the nozzle for extruder 2. (C)"),
        ('nozzle_2_filament', float, 1.75, (1.0, 3.5), "The diameter of the filament for extruder 2. (mm)"),
        ('nozzle_2_diam', float, 0.4, (0.1, 1.5), "The diameter of the nozzle for extruder 2. (mm)"),
        ('nozzle_2_xoff', float, 0, (-100, 100), "The X positional offset for extruder 2. (mm)"),
        ('nozzle_2_yoff', float, 0.0, (-100, 100), "The Y positional offset for extruder 2. (mm)"),
        ('nozzle_2_zoff', float, 0.0, (-100, 100), "The Y positional offset for extruder 2. (mm)"),
        ('nozzle_2_max_speed', float, 75.0, (0., 200.), "The maximum speed when using extruder 2. (mm/s)"),
        ('nozzle_2_feed_rate', float, 15.0, (0., 25.), "The feed_rate when using extruder 2. (mm/s)"),
        ('nozzle_2_flow_rate', float, 0.5, (0., 1.), "The flow_rate when using extruder 2."),
        ('nozzle_2_pre_extrude', float, 0.5, (0., 1.), "The pre extrusion when using extruder 2."),
        ('nozzle_2_retract', float, 0.5, (0., 1.), "The retract when using extruder 2."),

        ('nozzle_3_temp', int, 190, (150, 250), "The temperature of the nozzle for extruder 3. (C)"),
        ('nozzle_3_filament', float, 1.75, (1.0, 3.5), "The diameter of the filament for extruder 3. (mm)"),
        ('nozzle_3_diam', float, 0.4, (0.1, 1.5), "The diameter of the nozzle for extruder 3. (mm)"),
        ('nozzle_3_xoff', float, 0.0, (-100, 100), "The X positional offset for extruder 3. (mm)"),
        ('nozzle_3_yoff', float, 0, (-100, 100), "The Y positional offset for extruder 3. (mm)"),
        ('nozzle_3_zoff', float, 0.0, (-100, 100), "The Y positional offset for extruder 3. (mm)"),
        ('nozzle_3_max_speed', float, 75.0, (0., 200.), "The maximum speed when using extruder 3. (mm/s)"),
        ('nozzle_3_feed_rate', float, 15.0, (0., 25.), "The feed_rate when using extruder 3. (mm/s)"),
        ('nozzle_3_flow_rate', float, 0.5, (0., 1.), "The flow_rate when using extruder 3."),
        ('nozzle_3_pre_extrude', float, 0.5, (0., 1.), "The pre extrusion when using extruder 3."),
        ('nozzle_3_retract', float, 0.5, (0., 1.), "The retract when using extruder 3."),
    ))
])
3